name: Build LibWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - jdcloud_re-ss-01
          - link_nn6000-v1
          - link_nn6000-v2
          - qihoo_360v6
          - xiaomi_ax1800
          - zn_m2
          - cmcc_rax3000m_nand
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Execution Permissions
      run: chmod +x build.sh Scripts/*.sh

    - name: Setup Environment
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libfuse-dev libssl-dev libtool lrzsz \
        genisoimage msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils \
        rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: Build LibWrt for ${{ matrix.device }}
      run: ./build.sh -D ${{ matrix.device }}

    - name: Upload Artifacts for ${{ matrix.device }}
      uses: actions/upload-artifact@v4
      with:
        name: libwrt-firmware-${{ matrix.device }}
        path: openwrt/bin/targets/
